#!/bin/bash

# Disallow shell questions
export DEBIAN_FRONTEND=noninteractive

# Part 1. Outgoing mail only
#http://terraltech.com/opendkim-to-sign-postfix-mails-on-ubuntu/

apt-get install -y postfix opendkim opendkim-tools || exit 1

# Files might be generated on every boot
KEYDIR=/home/app/generated/mail

# Create once, stored on host system
KEYFILE=/home/app/srv/mail/private.key

# DKIM name
SELECTOR=mail


grep -qE '^SOCKET="inet:8891@localhost"' /etc/default/opendkim || echo 'SOCKET="inet:8891@localhost"' >> /etc/default/opendkim

grep -qE '# ** dish setup **' /etc/opendkim.conf || {

cat >> /etc/opendkim.conf <<EOF

# ** dish setup **

Selector $SELECTOR

# Identifies a set internal hosts whose mail should be signed rather than verified.
InternalHosts $KEYDIR/dkimhosts
# Identifies a set of "external" hosts that may send mail through the server as one of the signing domains without credentials as such.
ExternalIgnoreList $KEYDIR/dkimhosts

# outgoing only
Mode s

# список ключей -
KeyTable file:$KEYDIR/keytable
# соответствие адресов/доменов и ключей -
SigningTable file:$KEYDIR/signingtable

# на время отладки включим расширенное логгирование
LogWhy yes
X-Header yes

EOF
}

grep -qE '# ** dish setup **' /etc/postfix/main.cf || {

cat >> /etc/postfix/main.cf <<EOF

# ** dish setup **

# DKIM
milter_default_action = accept
milter_protocol = 2
smtpd_milters = inet:localhost:8891
non_smtpd_milters = inet:localhost:8891

EOF
}

# allow LAN relay
postconf -e "mynetworks = 172.17.0.0/16 127.0.0.0/8"


[ -f /etc/postfix/boot.sh ] || cat >> /etc/postfix/boot.sh <<EOD

[ -d $KEYDIR ] || mkdir -p $KEYDIR
[ -f $KEYFILE ] || openssl genrsa -out $KEYFILE 1024
openssl rsa -in $KEYFILE -out $KEYDIR/public.key -pubout -outform PEM
chmod 600 $KEYFILE
chown opendkim $KEYFILE

[ -f $KEYDIR/keytable ] || cat > $KEYDIR/keytable <<EOF
$SELECTOR._domainkey.\$MAILDOMAIN \$MAILDOMAIN:$SELECTOR:$KEYFILE
EOF

[ -f $KEYDIR/signingtable ] || cat > $KEYDIR/signingtable <<EOF
\$MAILDOMAIN $SELECTOR._domainkey.\$MAILDOMAIN
EOF

[ -f $KEYDIR/dkimhosts ] || cat >> $KEYDIR/dkimhosts <<EOF
127.0.0.1
localhost
172.17.0.0/16
\$MAILDOMAIN
EOF

KEYPUB=\$(head -n 5 $KEYDIR/public.key | tail -n +2 | tr -d '\n')

cat <<EOF
; *****************************************************************************
; ** You should add these DNS entries:

$SELECTOR._domainkey.\$MAILDOMAIN	TXT	"v=DKIM1; k=rsa; p=\$KEYPUB"
_adsp._domainkey.\$MAILDOMAIN		TXT	"dkim=all"
\$MAILDOMAIN				TXT	"v=spf1 ip4:YOUR_EXT_IP a:\$MAILDOMAIN ~all"

; *****************************************************************************
EOF

EOD

add_init '[[ "$MAILDOMAIN" ]] || MAILDOMAIN=localhost.localdomain'
add_init 'postconf -e "myhostname = $MAILDOMAIN"'
add_init '. /etc/postfix/boot.sh'

add_service opendkim
add_service postfix
add_port 25
