#!/bin/bash
# -------------------------------------------------------------------------------
# Postgresql - stage1 (cached)
# http://docs.docker.io/en/latest/examples/postgresql_service/

V=$1
[[ "$V" != "--" ]] || V=9.1

require server

if [[ "$V" == "9.2" ]] ; then
  add-apt-repository -y ppa:pitti/postgresql
  apt-get update
elif [[ "$V" == "9.3" ]] ; then
  echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main" > /etc/apt/sources.list.d/pgsql-9.3.list
  wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  apt-get update
fi

apt-get -y --force-yes install postgresql-$V postgresql-client-$V postgresql-contrib-$V postgresql-plperl-$V || 
  { echo "PG packages install problems" ; exit 1; }

# allow connect from host machine
echo "host  all all 172.17.0.0/16 md5" >> /etc/postgresql/$V/main/pg_hba.conf
# listen network
echo "listen_addresses = '*'"  >> /etc/postgresql/$V/main/postgresql.conf

# Create primary database objects
# plperl
# users op & apache

echo "Postgresql initial setup"
[ -a /var/run/postgresql/.s.PGSQL.5432 ] || /etc/init.d/postgresql start

[ -a /var/run/postgresql/.s.PGSQL.5432 ] || { echo "PG socket does not exists" ; exit 1; }

sudo -u postgres createlang plperl template1
sudo -u postgres createuser -d -r -s op
sudo -u postgres createdb -O op op

sudo -u postgres psql -c "create user apache password 'apache'" template1

/etc/init.d/postgresql stop

cat >> /etc/supervisor/conf.d/postgresql-$V.conf <<EOF
[program:postgresql-$V]
command=/usr/lib/postgresql/$V/bin/postgres -D /var/lib/postgresql/$V/main -c config_file=/etc/postgresql/$V/main/postgresql.conf
user=postgres
autorestart=true
stopsignal=INT
EOF

# EXPOSE 5432
add_port 5432

