#!/bin/bash

# -------------------------------------------------------------------------------
# SSH user

# Get name from dish or shell args
NEWUSER=$1
[[ "$NEWUSER" && "$NEWUSER" != "--" ]] || NEWUSER=op

# Cloud host default key
KEY0=~/.ssh/authorized_keys

# Dish host  default key
KEY1=/home/app/op/.ssh/authorized_keys

HOMEDIR=/home/app/$NEWUSER

# Check if user exists already
grep -qe "^$NEWUSER:" /etc/passwd || useradd -d $HOMEDIR -m -r -s /bin/bash -Gwww-data -gusers $NEWUSER

[ -d $HOMEDIR/.ssh ] ||  sudo -u $NEWUSER mkdir -m 700 $HOMEDIR/.ssh

[ -f $HOMEDIR/.ssh/authorized_keys ] || {
  key=""
  if [ -f $KEY0 ] ; then
    key=$KEY0
  elif [ -f $KEY1 ] ; then
    key=$KEY1
  else
    echo "WARNING: ssh key not found"
  fi
  [[ "$key" ]] && {
    echo "Using pub key $key"
    cat $key | head -1 > $HOMEDIR/.ssh/authorized_keys
    chown $NEWUSER $HOMEDIR/.ssh/authorized_keys
    chmod 600 $HOMEDIR/.ssh/authorized_keys
  }
}

[ -f /etc/sudoers.d/$NEWUSER ] || {
  echo "$NEWUSER ALL=NOPASSWD:ALL" > /etc/sudoers.d/$NEWUSER
  chmod 440 /etc/sudoers.d/$NEWUSER
}


cat <<EOF
User $NEWUSER setup complete
You should ssh login via $NEWUSER now
EOF
